#!/usr/bin/env bash
# Install Nginx on the server with redirect to youtube

apt-get update
apt-get install nginx -y

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Set up redirection in the Nginx configuration file
echo "server {
    listen 80;
    server_name localhost;
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" >> /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

# Create a temporary index.html file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Check if Nginx is running and serving "Hello World!" on port 80
curl -s localhost | grep -q "Hello World!"
