#!/usr/bin/env bash
# Install Nginx on the server

apt-get update
apt-get install nginx -y

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create the custom 404 error page
cat << EOF > /var/www/html/404.html
Ceci n'est pas une page
EOF

# Update the Nginx configuration to use the custom error page
sed -i '/location \/ {/a \
\    error_page 404 /404.html;\n' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
