#!/usr/bin/env bash
# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

# Update the package lists for upgrades and new package installations
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Create a configuration snippet to add the custom header
echo "add_header X-Served-By $HOSTNAME;" | sudo tee /etc/nginx/snippets/custom-header.conf

# Modify the Nginx default configuration file to include the custom header
sudo sed -i '/server_name _;/a include snippets/custom-header.conf;' /etc/nginx/sites-available/default

# Test the configuration
sudo nginx -t

sudo systemctl reload nginx
