#!/usr/bin/env bash
#Install haproxy load balancer to mediate connections to web-01 and web-02

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/harproxy

# Configure HAproxy
cat << EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
   bind *:80
     stats uri /haproxy?stats
     default_backend http_back

backend http_back
   balance roundrobin
   server web1 54.160.115.226:80 check
   server web2 100.25.139.174:80 check
EOF

# Enable HAproxy to be managed via an init script
service haproxy enable
# Restart HAproxy to apply the changes
service haproxy start
