#!/usr/bin/env bash

# MySQL user
USER='root'

# MySQL password
PASSWORD=$1

# Date format for the backup file
DATE=$(date +%d-%m-%Y)

# MySQL dump file name
DUMP_FILE='backup.sql'

# Compressed file name
ARCHIVE_FILE="${DATE}.tar.gz"

# Dump all databases
mysqldump -u ${USER} -p${PASSWORD} --all-databases > ${DUMP_FILE}

# Compress the dump file
tar -czvf ${ARCHIVE_FILE} ${DUMP_FILE}

# Remove the dump file
rm ${DUMP_FILE}

echo "Backup created: ${ARCHIVE_FILE}"
