#!/usr/bin/env bash
# Copy all of databases in server for manual backup
USER='root'

PASSWORD=$1

# Date format for the backup file
DATE=$(date +%d-%m-%Y)

DUMP_FILE='backup.sql'

# Compressed file name
ARCHIVE_FILE="${DATE}.tar.gz"

# Dump all databases
mysqldump -u ${USER} -p${PASSWORD} --all-databases > ${DUMP_FILE}

# Compress the dump file
tar -czvf ${ARCHIVE_FILE} ${DUMP_FILE}

echo "Backup created: ${ARCHIVE_FILE}"
