#!/usr/bin/env bash
#Print a time for 12 hours and 59min with a while loop
m=1
while [ $m -lt 101 ]
do
	if [ $((m % 3)) -eq 0 ] && [ $((m % 5)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((m % 3)) -eq 0 ]; then
		 echo "Fizz"
	elif [ $((m % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$m"
	fi
	
	m=$((m + 1))
done
