#! /usr/bin/env bash
#Change local host and faebook ip in hosts file
# Copy the existing hosts file to a new location
cp /etc/hosts ~/hosts.new

# Use sed to replace '127.0.0.1 localhost' with '127.0.0.2 localhost'
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' ~/hosts.new

# Add a new line to resolve facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Copy the modified hosts file back to /etc/hosts
cp -f ~/hosts.new /etc/hosts
