#!/usr/bin/env bash
#Script listens to port 98

# Check if netcat is installed
if ! command -v nc &> /dev/null
then
    echo "Netcat could not be found. Please install it and try again."
	    exit
		fi

# Listen on port 98
while true; do
    nc -l localhost 98
	done
