#!/usr/bin/env bash
# Change the user running Nginx to nginx
USERNAME="nginx"
if id -u "$USERNAME" >/dev/null 2>&1; then
	sudo sed -i "s/user .*/user $USERNAME;/" /etc/nginx/nginx.conf
	sudo systemctl restart nginx
fi
